version: devel-0006
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /update
  script: src.update.app
  login: admin
- url: /api/.*
  script: src.api.app
- url: /clean
  script: src.clean.app
  login: admin

libraries:
- name: ssl
  version: latest
