version: devel-0002
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /update
  script: src.update.app
  login: admin
- url: /api/.*
  script: src.api.app
- url: /extract
  script: src.extract.app

libraries:
- name: ssl
  version: latest
